{ extends: [
            # 'stylelint-config-standard',
            'stylelint-config-prettier',
            'stylelint-prettier/recommended',
            'stylelint-config-standard-scss',
            'stylelint-config-prettier-scss',
            # 'stylelint-scss',
        ], rules: { 'prettier/prettier': ['error', { 'endOfLine': 'auto' }] } }
