{
    extends: [
            'stylelint-config-standard',
            'stylelint-config-prettier',
            'stylelint-prettier/recommended',
            # 'stylelint-scss',
        ],
    # rules: {
    #   "at-rule-no-unknown": [
    #     true,
    #     {
    #       ignoreAtRules: [
    #         "tailwind",
    #         "apply",
    #         "variants",
    #         "responsive",
    #         "window",
    #       ],
    #     },
    #   ],
    #   "declaration-block-trailing-semicolon": null,
    #   "no-descending-specificity": null,
    # },
}
