{
    extends:
        [
            'stylelint-config-standard',
            'stylelint-config-prettier',
            'stylelint-prettier/recommended',
        ],
    # rules: {
    #   "at-rule-no-unknown": [
    #     true,
    #     {
    #       ignoreAtRules: [
    #         "tailwind",
    #         "apply",
    #         "variants",
    #         "responsive",
    #         "screen",
    #       ],
    #     },
    #   ],
    #   "declaration-block-trailing-semicolon": null,
    #   "no-descending-specificity": null,
    # },
}

# module.exports =
# {
#   extends:   [
#     "stylelint-config-standard",
#     "stylelint-config-prettier",
#     "stylelint-prettier/recommended",
#   ],
#   rules: {
#     "at-rule-no-unknown": [
#       true,
#       {
#         ignoreAtRules: [
#           "tailwind",
#           "apply",
#           "variants",
#           "responsive",
#           "screen",
#         ],
#       },
#     ],
#     "declaration-block-trailing-semicolon": null,
#     "no-descending-specificity": null,
#   },
# };
